[package]
name = "ttest"
version = "0.1.0"
edition = "2021"
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
description = "TTest"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/VladasZ/ttest"
repository = "https://github.com/VladasZ/ttest"

[dependencies]
